config/routes.rb
Rails.application.routes.draw do
  root 'dashboards#show'

  mount ActionCable.server => '/cable'

  resource :users, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resources :chatrooms, except: [:destroy, :edit] do
    resources :messages, except: [:destroy, :edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :authors, through: :messages
  validates :topic, presence: true, uniqueness: true, case_sensitive: false
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :author, class_name: User, foreign_key: :user_id

  delegate :username, to: :author, allow_nil: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :chatrooms, through: :messages
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @chatrooms = Chatroom.all
    @chatroom = Chatroom.new
  end

  def new
    @chatroom = Chatroom.new
  end

  def show
    @chatroom = Chatroom.includes(:messages, :authors).find(params[:id])
    @message = Message.new
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)
    if @chatroom.save
      redirect_to chatrooms_path
    else
      render :new
    end
  end

  private

  def chatroom_params
    params.require(:chatroom).permit(:topic)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_room

  def new
    @message = @chatroom.messages.new
  end

  def create
    message = @chatroom.messages.new(message_params)
    if message.save
      ActionCable.server.broadcast 'messages',
        message: message.content,
        user: message.username
      head :ok
    else
      redirect_to chatrooms_path
    end
  end

  private

  def find_room
    @chatroom = Chatroom.find(params[:chatroom_id])
  end

  def message_params
    params.require(:message).permit(:content).merge(user_id: current_user.id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_username(params[:session][:username])
    if @user
      session[:user_id] = @user.id
      redirect_to chatrooms_path
    else
      render :new, status: 404
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_sessions_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatrooms/_chatroom.html.slim
li
  = link_to chatroom do
    .mui-panel.mui--z1
      = chatroom.topic

app/views/chatrooms/index.html.slim
.mui-container-fluid
  .mui--text-center
    h2 Chatrooms
  .mui-panel.mui--z2
    = simple_form_for @chatroom do |f|
      = f.input :topic, label: false, wrapper_html: {class: 'mui-textfield'}, placeholder: 'Topic name'
      = f.button :submit, 'Create chatroom', class: 'mui-btn mui-btn--raised'
  ul
    = render @chatrooms

app/views/chatrooms/show.html.slim
.mui-container-fluid
  .mui--text-center
    h2
      ' Messages for
      span style='color: blue;'
        = @chatroom.topic
  .mui-panel.mui--z2
    = simple_form_for [@chatroom, @message], remote: true, authenticity_token: true do |f|
      = f.input :content, label: false, wrapper_html: {class: 'mui-textfield'}, placeholder: 'Topic name'
      = f.button :submit, 'Say to room', class: 'mui-btn mui-btn--raised'
  ul#messages
    = render partial: 'messages/message', collection: @chatroom.messages

app/views/dashboards/show.html.slim
.mui-container-fluid
  .mui-panel.mui--z2
    .mui--text-center
      .mui--text-display3
        | Welcome to Chatty!
      .mui--text-headline
        | The Rails 5 + Action Cable example app
      | Sign up or log in, then create a chatroom or browse existing rooms to start chatting.

app/views/layouts/application.html.slim
doctype html
html
  head
    title ActionCableExample
    = csrf_meta_tags

    = action_cable_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = stylesheet_link_tag  '//cdn.muicss.com/mui-0.7.0/css/mui.min.css'
    = javascript_include_tag '//cdn.muicss.com/mui-0.7.0/js/mui.min.js'
  body
    nav.mui-container-fluid
      .mui-appbar
        table width='100%'
          tr style='vertical-align:middle;'
            td.mui--appbar-height
              h1.gutter-right
                a href='/' Web Sockets
            - if logged_in?
              td
                h3
                  = link_to 'Chatrooms', chatrooms_path
            td.mui--appbar-height align='right'
              - if logged_in?
                h2
                  = fa_icon 'user 2x', class: 'gutter-right'
                  = link_to 'Logout', sessions_path, method: :delete
              - else
                h2
                  = link_to 'Log in', new_sessions_path, class: 'gutter-right'
                  = link_to 'Sign up', new_users_path
    = yield

app/views/messages/_message.html.slim
li
  strong.text-blue
    = "#{message.username}: "
  = message.content

app/views/users/new.html.slim
.mui-container-fluid
  .mui--text-center
    h2 SIGN UP
  .mui-panel.mui--z2
    = simple_form_for @user do |f|
      = f.input :username, label: false, wrapper_html: { class: 'mui-textfield' }, placeholder: 'User name'
      = f.button :submit, class: 'mui-btn mui-btn--raised'